"""seeder models

Revision ID: 1d2ca01e6e8d
Revises: aefebcbc919e
Create Date: 2025-11-27 20:27:32.362212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d2ca01e6e8d'
down_revision: Union[str, Sequence[str], None] = 'aefebcbc919e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_uploads',
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('s3_bucket', sa.String(length=100), nullable=False),
    sa.Column('s3_region', sa.String(length=50), nullable=False),
    sa.Column('s3_etag', sa.String(length=100), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_extension', sa.String(length=10), nullable=True),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('virus_scanned', sa.Boolean(), nullable=False),
    sa.Column('virus_scan_status', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_uploads_id'), 'file_uploads', ['id'], unique=False)
    op.create_index(op.f('ix_file_uploads_s3_key'), 'file_uploads', ['s3_key'], unique=True)
    op.create_table('seeder_executions',
    sa.Column('seeder_name', sa.String(length=100), nullable=False),
    sa.Column('seeder_type', sa.Enum('INITIAL', 'UPDATE', 'RESET', 'RESTORE', name='seedertype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'ROLLED_BACK', name='seederstatus'), nullable=False),
    sa.Column('records_created', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_deleted', sa.Integer(), nullable=False),
    sa.Column('backup_s3_key', sa.String(length=500), nullable=True),
    sa.Column('backup_file_size', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.Column('executed_by_id', sa.Integer(), nullable=True),
    sa.Column('execution_metadata', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seeder_executions_id'), 'seeder_executions', ['id'], unique=False)
    op.create_index(op.f('ix_seeder_executions_seeder_name'), 'seeder_executions', ['seeder_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seeder_executions_seeder_name'), table_name='seeder_executions')
    op.drop_index(op.f('ix_seeder_executions_id'), table_name='seeder_executions')
    op.drop_table('seeder_executions')
    op.drop_index(op.f('ix_file_uploads_s3_key'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_uploads_id'), table_name='file_uploads')
    op.drop_table('file_uploads')
    # ### end Alembic commands ###
